### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by theodorosploumis** [eworx-org/drupal-js#1]
- [x] Ask for feedback, suggestions and improvements
- [x] Create a ToC on top
- [x] Add CONTRIBUTE template for new issues, enforce Forks and PRs so everyone watching gets the updates.
- [x] Add tags for GH search
- [x] Add a Table of Requirements example for Drupal + JS functionalities (see issue #6)
- [ ] Add a Releases strategy
- [ ] Share on D.O., Drupal Slack channels, Social media (twitter etc)
